### PR TITLE
Bug 1719315 - Add documentation about the URL metric type

### PR DESCRIPTION
**Pull request by brizental**
Blocked until a release of Glean.js comes out with https://github.com/mozilla/glean.js/pull/529.

### CODE REVIEW

**Comment by brizental** [comment]
[v0.17.0](https://github.com/mozilla/glean.js/releases/tag/v0.17.0) is out with the new type :)

**Review by travis79 — COMMENTED** [review]
I'm good with everything here, but I'm withholding approval in order to put on my data-steward hat for a moment and ask about the data sensitivity category for this particular metric type.  I feel that calling out more explicitly here in our docs that URL metrics will almost always be Category 3 and above would be a good way to reduce overuse and ensure that it gets data-reviewed properly.  What do you think?

**Comment by brizental** [comment]
> I'm good with everything here, but I'm withholding approval in order to put on my data-steward hat for a moment and ask about the data sensitivity category for this particular metric type. I feel that calling out more explicitly here in our docs that URL metrics will almost always be Category 3 and above would be a good way to reduce overuse and ensure that it gets data-reviewed properly. What do you think?

Agreed 100%. Let me make the change :)

**Comment by brizental** [comment]
I added a note, let me know if you think it is too hidden. I also filed a bug to maybe reject that on glean_parser directly https://bugzilla.mozilla.org/show_bug.cgi?id=1721358.

**Review by travis79 — APPROVED** [review]
Thanks for adding the data sensitivity note, this LGTM!

**Pull request merged**
