### PR TITLE
Use correct name for environment variable

### PR DESCRIPTION
**Pull request by badboy**
### Pull Request checklist ###

- [ ] **Quality**: This PR builds and tests run cleanly
  - `make test` runs without emitting any warnings
  - `make lint` runs without emitting any errors
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry or an explanation of why it does not need one
  - Any breaking changes to language binding APIs are noted explicitly

### CODE REVIEW

**Comment by mdboom** [comment]
Hmm...  I have `ANDROID_NDK_ROOT` in my environment (not `ANDROID_NDK_HOME`).  But I think I set that up prior to @Dexterp37 updating these docs based on changes in a-s.

I think if these instructions "work for you", that's fine.  (At least, I think `NDK_HOME` was always a typo).

**Comment by badboy** [comment]
Ah, now I'm confused.
This is what application-services says: https://github.com/mozilla/application-services/blob/master/docs/howtos/setup-android-build-environment.md#prepare-your-build-environment

> ... and set ANDROID_NDK_ROOT to this location.
> Set ANDROID_NDK_HOME to match ANDROID_NDK_ROOT, for compatibility with some android grandle plugins.

And now I'm confused which one I set first and it worked.

**Comment by mdboom** [comment]
Yeah, me too.  I can tell you I have only `ANDROID_NDK_ROOT` set, and it works.  But consider that anecdotal from someone who doesn't really understand the details :)

**Comment by badboy** [comment]
I changed it to `ANDROID_SDK_ROOT`

**Comment by badboy** [comment]
> Yes, that was a typo. Tbh, I now only have `ANDROID_HOME ` and all works just fine..

Gosh, this is confusing. I unset both in my Linux VM and it still compiles. Maybe it just breaks if it needs to setup the toolchains to begin with? Not sure, but this patch at least is more correct than it was before.

**Pull request merged**
