### PR TITLE
Bug 1800620 - Remove `glean.validation.first_run_hour`

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
draft while I re-read the history and figure out if it's ok to remove.

**Comment by badboy** [comment]
I couldn't find any analysis done based on this metric as called out in https://bugzilla.mozilla.org/show_bug.cgi?id=1680783

**Review by perrymcmanis144 — APPROVED** [review]
Matches my expectation for removing first_run_hour, tests pass and no one has objected so LGTM 👍

**Comment by badboy** [comment]
blocked while I wait for the feedback period.

**Pull request merged**
