### PR TITLE
Sync Gradle dependencies with the versions used in AC

### PR DESCRIPTION
**Pull request by rvandermeulen**

### CODE REVIEW

**Comment by rvandermeulen** [comment]
Changelog update will need a bit of merging with #2860.

**Comment by chutten** [comment]
Rerouting to Travis who'll be able to better ensure this doesn't have unintended consequences.

**Comment by rvandermeulen** [comment]
Test failure is a known intermittent:
```
java.lang.AssertionError: Ping payload: {"client_info":{"android_sdk_version":"34","app_build":"0.0.1","app_display_version":"0.0.1","architecture":"armeabi-v7a","build_date":"2024-06-03T14:24:04+00:00","client_id":"949db7d4-1577-4c6f-baaf-319d01e295d0","device_manufacturer":"robolectric","device_model":"robolectric","first_run_date":"2024-06-03+00:00","locale":"en-US","os":"Linux","os_version":"14","telemetry_sdk_build":"60.3.0"},"metrics":{"counter":{"glean.error.preinit_tasks_overflow":16,"telemetry.repeatedly":999},"memory_distribution":{"glean.database.size":{"sum":82,"values":{"82":1,"86":0}}}},"ping_info":{"end_time":"2024-06-03T14:24:04.639+00:00","seq":0,"start_time":"2024-06-03T14:24:04.549+00:00"}} expected:<1000> but was:<999>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at mozilla.telemetry.glean.GleanTest.overflowing the task queue records telemetry(GleanTest.kt:685)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:489)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:290)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:104)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
	Suppressed: org.robolectric.android.internal.AndroidTestEnvironment$UnExecutedRunnablesException: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(Looper.getMainLooper()).idle() call.
```

**Review by travis79 — APPROVED** [review]
Should be fine, I don't see anything scary in the update changelogs.

**Pull request merged**
