### PR TITLE
Bug 1770901 - CI: Update to newer Python 3.8 images for newer Ubuntu, which has a newer wine

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
At least they are running again...

**Comment by badboy** [comment]
Not quite intermittent free, but a start. Gonna file a bug for the now-skipped tests.

**Review by chutten — COMMENTED** [review]
PR title says 3.10, changes unpin our 3.8.5 to 3.8.whatever...

**Comment by badboy** [comment]
> PR title says 3.10, changes unpin our 3.8.5 to 3.8.whatever...

hah, because it was 3.10 at first, but we actually need to stay on 3.8
and `cimg/python:3.8` gives us whatever latests python 3.8 circleci has, whereas `:3.8.5` is some old version based on ubuntu 18

**Review by chutten — APPROVED** [review]

**Pull request merged**
