### PR TITLE
The big UniFFIcation: May it be one.

### PR DESCRIPTION
**Pull request by badboy**
Here we are. 7 months ago the `uniffi` branch was created and work started.
There were a ton of changes, countless recompiles, different approaches, upstream fixes, back-and-forth, testing across nearly all our consumers, frustration, happyness, small wins, big wins.

Overall we now have a Glean that's a whole bunch less code, a whole bunch more logic in a single language.
And hopefully so few visible changes that no one will ever notice anything happens (they will...).

I'm now reasonably confident that this code works across all our consumers and would like to get it merged and released.

There have been some changes to outside facing APIs and the docs around these have not been universally updated yet.
I don't want that to be a blocker for the release though, as we can change our docs easily in between releases.
Some of them breaking (thus deserving a proper callout in the changelog), some less.

We also do not yet have updated docs on how this all works together and how to extend it with new metric types. While I will get started on that I also don't think this should block the release.

How do we go about this? This PR is **MASSIVE** and near impossible to review by any single person really.
Now the good thing is that this wasn't developed in secret and each step was gradually reviewed in the past (a huge thanks to @travis79 for the majority of the work there).
Thus I would say we move ahead without an extra formal review here.

What's left to do (in no particular order):

* [ ] Update some docs / line up the docs work (at least write down _what_ needs to be changed)
* [ ] Prepare the changelog entries. This is a blocker. I want to do it as part of this PR.
* [ ] Merge the [glean_parser changes](https://github.com/mozilla/glean_parser/pull/481). Necessary and then we land the update here as well.
* [ ] One last pass over my notes and the code to ensure there's no critical todo or fixme left undone.

### CODE REVIEW

**Comment by badboy** [comment]
Some statistics:

Lines of code in current `main`:

```
===============================================================================
 Language            Files        Lines         Code     Comments       Blanks
===============================================================================
 C                       1           71           47           10           14
 C Header                3         1673          754          598          321
 Kotlin                 77        13620         8436         3363         1821
 Python                 61         9235         6701          594         1940
 Swift                  57         8866         5234         2350         1282
-------------------------------------------------------------------------------
 Rust                  155        24486        18390         2358         3738
 |- Markdown           114         3999           84         2806         1109
 (Total)                          28485        18474         5164         4847
===============================================================================
 Total                 354        57951        39562         9273         9116
===============================================================================
```

Lines of code in this branch:

```
===============================================================================
 Language            Files        Lines         Code     Comments       Blanks
===============================================================================
 C Header                1           15            4            6            5
 Kotlin                 70        10147         6519         2262         1366
 Python                 44         6204         4467          421         1316
 Swift                  52        11275         7465         1941         1869
-------------------------------------------------------------------------------
 Rust                  113        21200        15881         2059         3260
 |- Markdown            89         3801           58         2674         1069
 (Total)                          25001        15939         4733         4329
===============================================================================
 Total                 280        48841        34336         6689         7816
===============================================================================
```

Now you might think: "That's not even that much less code" and you are right, BUT ...

* No more manually written JNA "header file" so to speak.
* No more cbindgen-generated header file we need to check-in (though UniFFI does that on the fly for us now where needed).
* A whole _bunch_ of code is in tests (5000 LoC of Kotlin, 2600 LoC of Swift, 2300 LoC of Python)
* API definitions of all the metric types in a single place and _instant_ implementation for all foreign-language SDKs (sometimes a couple of extra lines are needed to make the API nicer)

**Review by Dexterp37 — CHANGES_REQUESTED** [review]
I think that looks scary and good with the rust/TC tests fixed. I'll give one last look after tests pass.

**Review by Dexterp37 — APPROVED** [review]
Great job. Thanks all for the work on this multi-months effort, especially @badboy and @travis79 .

**Review by travis79 — APPROVED** [review]
This is a huge step, @badboy !!  Amazing, awesome, 🎉 !

**Pull request merged**
