### PR TITLE
Update glean_parser to v1.9.5

### PR DESCRIPTION
**Pull request by brizental**

### CODE REVIEW

**Comment by brizental** [comment]
@mdboom thanks for the review, Mike. I just realized that I had updated the glean_parser version incorrectly the previous times. Lesson learned :)

Also, mozilla-mobile/android-components#4820. The android-components PR.

**Comment by badboy** [comment]
> And (sorry), I think this is still missing one place in `/samples/ios/app/sdk_generator.sh`.

That file is a symlink to the other sdk_generator.sh

**Comment by badboy** [comment]
and we got a bug for making it consistent: https://bugzilla.mozilla.org/show_bug.cgi?id=1590448

**Comment by mdboom** [comment]
Oh, sorry about that.  Grep showed that as separate hits for me and didn't
think to look that it was a symlink...

**Pull request merged**
