### PR TITLE
[Bug 1799509] Add count to timing_distribution

### PR DESCRIPTION
**Pull request by scholtzan**
Not sure if this needs to be updated manually, but those changes are the same as done in https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/750

### CODE REVIEW

**Review by chutten — APPROVED** [review]
Do we also need this for `custom_distribution` and `memory_distribution`? I think all the `*_distribution` share the same payload format.

**Comment by scholtzan** [comment]
> Do we also need this for custom_distribution and memory_distribution? I think all the *_distribution share the same payload format.

yes, you are right. There are some `count`s coming from `memory_distribution` and `custom_distribution` that are written to `additional_properties`

**Comment by badboy** [comment]
We have a script to update the schema and a CI task that checks it against upstream: https://app.circleci.com/jobs/github/mozilla/glean/191530

**Comment by badboy** [comment]
Let's wait for it to land in MPS and then merge here.

**Comment by scholtzan** [comment]
https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/750 has been merged

**Pull request merged**
