### PR TITLE
On shutdown kill the dispatcher if Glean failed to initialize

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Review by Dexterp37 — DISMISSED** [review]
Good catch. Please add a changelog entry.

**Comment by badboy** [comment]
> Good catch. Please add a changelog entry.

This is UniFFI. `main` is doing the right thing.
CI will continue to be broken for a bit for UniFFI.

**Comment by Dexterp37** [comment]
Gosh, sorry :\

**Comment by badboy** [comment]
Merging without review. It unblocks the test!

**Pull request merged**
