### PR TITLE
Add Kotlin docs to CI

### PR DESCRIPTION
**Pull request by mdboom**
This is an experimental follow-on to link to the Kotlin docs from the mdbook content and then run on CI and deploy all together.

### Pull Request checklist ###

- [ ] **Quality**: This PR builds and tests run cleanly
  - `make test` runs without emitting any warnings
  - `make lint` runs without emitting any errors
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry or an explanation of why it does not need one
  - Any breaking changes to language binding APIs are noted explicitly

### CODE REVIEW

**Comment by mdboom** [comment]
I'm not quite sure how to test that the `persist_to_workspace` of overlapping paths like this works until it actually deploys the docs and we can inspect.  @badboy: May you have an idea?  I also think it's fairly low risk to just merge and test afterward.

**Comment by badboy** [comment]
Hm, looks like the kotlin doc task is already failing.

**Comment by Dexterp37** [comment]
> 
> 
> Hm, looks like the kotlin doc task is already failing.

Is it? Looks like CI is green and there's no error immediately standing out for me in the logs :|

**Comment by mdboom** [comment]
I just rebased and force-pushed to get the tests to run again.  We'll see what they do...

**Comment by mdboom** [comment]
Hmm...  Kotlin docs failed again this time.  Interkittens...

**Pull request merged**
