### PR TITLE
Bug 1811857, bug 1811888 - Fully remove support for the old events API

### PR DESCRIPTION
**Pull request by badboy**
Will require a glean_parser change.

### CODE REVIEW

**Review by travis79 — APPROVED** [review]
This seems worthy of a changelog entry noting the change from "deprecated" -> "removed", but other than that LGTM!

**Comment by badboy** [comment]
> This seems worthy of a changelog entry noting the change from "deprecated" -> "removed", but other than that LGTM!

Way ahead of you: https://github.com/mozilla/glean/blob/main/CHANGELOG.md#v5200-2022-12-13
The API has been removed in Glean v52. This just removes the internals for it.

**Comment by badboy** [comment]
Note that all other changes except the glean_parser update itself aren't visible to users so I didn't put them in the changelog

**Review by travis79 — APPROVED** [review]
Still looks good to me!

**Pull request merged**
