### PR TITLE
Bug 1869429 - Event extra key limit increased from 15 to 50 total keys

### PR DESCRIPTION
**Pull request by travis79**

### CODE REVIEW

**Review by badboy — CHANGES_REQUESTED** [review]
only doc, no code changes?

**Comment by travis79** [comment]
> only doc, no code changes?

Wait, what?!?!     I must have forgot to git-add some things before I committed this. I'll fix it

**Comment by badboy** [comment]
> > only doc, no code changes?
> 
> Wait, what?!?! I must have forgot to git-add some things before I committed this. I'll fix it

I figured :D

**Comment by travis79** [comment]
> > > only doc, no code changes?
> > 
> > 
> > Wait, what?!?! I must have forgot to git-add some things before I committed this. I'll fix it
> 
> I figured :D

Well, I've refreshed my memory where this validation occurs, and I can now better explain why this PR is doc-only: because the limit is imposed in glean_parser through the metrics schema. I'll open a PR to update the limit there, and there shouldn't be anything left for this PR so if you have time for a final review, that would be great!

**Comment by travis79** [comment]
> > Well, I've refreshed my memory where this validation occurs, and I can now better explain why this PR is doc-only: because the limit is imposed in glean_parser through the metrics schema. I'll open a PR to update the limit there, and there shouldn't be anything left for this PR so if you have time for a final review, that would be great!
> 
> I guess we need a parser release and update here then?

The glean_parser PR to update the limits is here: https://github.com/mozilla/glean_parser/pull/648

Once that is merged and released, I'll add the version bump to this PR and reflag you for review

**Review by badboy — APPROVED** [review]
code's good, CI will decide the rest

**Pull request merged**
