### PR TITLE
Bug 1598993 - Add convenience `measure` methods to TimingDistribution and Timespan metrics

### PR DESCRIPTION
**Pull request by travis79**
This adds convenience methods to simplify measuring a function or block of code to both Android and iOS.

### CODE REVIEW

**Comment by travis79** [comment]
This passes the Swift tests per `make test-swift`, I don't see any reason to run them again until the merge with master.

**Comment by mdboom** [comment]
Should we file bugs for adding this API to the other languages -- I don't think there's any reason we couldn't also do this there.

**Comment by travis79** [comment]
> Should we file bugs for adding this API to the other languages -- I don't think there's any reason we couldn't also do this there.

This adds it to both Kotlin and Swift. I wasn't sure how to accomplish this in Python, this relates to the 'higher order functions' question I was ask you about.  I'm happy to file bugs for the other languages, or to take a stab at adding them to this PR, whichever you think.

**Comment by mdboom** [comment]
Ah -- sorry I missed the Kotlin.  Maybe just file a bug for Python -- it's totally orthogonal so doesn't need to hold this up.

**Comment by travis79** [comment]
> Ah -- sorry I missed the Kotlin. Maybe just file a bug for Python -- it's totally orthogonal so doesn't need to hold this up.

[Bug filed](https://bugzilla.mozilla.org/show_bug.cgi?id=1624626), and I'd still like to learn how something like this is done in Python, so maybe you can point me in the right direction when we have time to chat.

**Pull request merged**
