### PR TITLE
iOS: Don't exclude arm64 build for the simulator

### PR DESCRIPTION
**Pull request by badboy**
This currently requires a local build of rustc with https://github.com/rust-lang/rust/pull/81966 to enable the target (and also LLVM 12, LLVM 11 untested). Thus we can't really land that before that becomes stable.

I think it would also require direct consumers to switch over to xcframeworks.
It's untested in app-services, I guess it _could_ work for Intel builds there, but this would need to be tested.

No need for a formal review or test yet.

* [ ] Wait for [upstream changes in rustc](https://github.com/rust-lang/rust/pull/81966)
* [ ] Test it on an Intel machine
* [ ] Test it in app-services

### CODE REVIEW

**Comment by travis79** [comment]
I'll be prototyping the "Better Builds" proposal next week, this may help me with packaging the iOS stuff as I'm sure that app-services will face a similar issue with this (as will Nimbus when we have iOS for it).

**Comment by badboy** [comment]
`aarch64-apple-ios-sim` is available now on Nightly ... sort of. One needs to build `libstd`, but cargo (nightly) can easily do that.
As this only affects developers on M1 machines (like me) we can land this in our build script and I can move my dev environment off a fork of our own code base that already used these changes.

**Review by travis79 — APPROVED** [review]
Note: reminder to file a bug to change this once the feature has made it to release in rustc.

**Comment by badboy** [comment]
> Note: reminder to file a bug to change this once the feature has made it to release in rustc.

That might or might not happen anytime soon unfortunately (we'll see, I'm in the rust zulip to see how we can push it forward)

**Comment by badboy** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1694605

**Pull request merged**
