### PR TITLE
Add instrumented tests to sample app

### PR DESCRIPTION
**Pull request by brizental**
Related to [Bug 1570252](https://bugzilla.mozilla.org/show_bug.cgi?id=1570252)

I basically just copy pasted the tests from the sample app in android components, so they should do the same thing.

Unfortunately (or fortunately depending on how you look at it) this tests are failing, because while adding them to the project we found two bugs in the actual glean app.

@badboy reported one of them ([Bug 1588717](https://bugzilla.mozilla.org/show_bug.cgi?id=1588717)) and is still loking into the other one.

The one bug that is already reported is also happening for the instrumented tests in android-components. Which means that they are not probably run on CI there, as well.

### CODE REVIEW

**Comment by badboy** [comment]
Ooooh, this is now failing the lint tests for the generated files.
Should we fix that or do we just want to ignore generated files completely, @Dexterp37?

**Comment by badboy** [comment]
While we're at it: we should probably document how to run them (`./gradlew connectedAndroidTest`) and/or add a make task for it.

**Comment by Dexterp37** [comment]
> 
> 
> Ooooh, this is now failing the lint tests for the generated files.
> Should we fix that or do we just want to ignore generated files completely, @Dexterp37?

I think this should be fixed: at the parsers level?

**Comment by brizental** [comment]
> we should probably document how to run them
@badboy I just added a commit adding some instructions on how to run the instrumented tests. Nothing super detailed... Let me know if it lookgs good :)

**Comment by Dexterp37** [comment]
@badboy @mdboom and @brizental what if we changed [this line](https://github.com/mozilla/glean/blob/3031fecaf4652d39e9a6539905c64156b97b61f7/glean-core/android/src/main/java/mozilla/telemetry/glean/utils/ThreadUtils.kt#L10) to make it visible from tests/make it overridable? Then we could just set that to the main thread value in the instrumented tests and be done with it :)

**Comment by badboy** [comment]
Seems hacky, but doable. I'd still like to find _any_ documentation whether this behavior is expected, but I was unable to find anything so far :(

**Comment by mdboom** [comment]
> @badboy @mdboom and @brizental what if we changed this line to make it visible from tests/make it overridable? Then we could just set that to the main thread value in the instrumented tests and be done with it :)

Yeah, I guess that would work.  I share @badboy's desire for documentation, though, but maybe it just doesn't exist.

**Comment by Dexterp37** [comment]
> 
> 
> @badboy @mdboom and @brizental what if we changed [this line](https://github.com/mozilla/glean/blob/3031fecaf4652d39e9a6539905c64156b97b61f7/glean-core/android/src/main/java/mozilla/telemetry/glean/utils/ThreadUtils.kt#L10) to make it visible from tests/make it overridable? Then we could just set that to the main thread value in the instrumented tests and be done with it :)

Ah, scrape that. This would work in mozilla/glean, but not in a-c. How would we fix it there?

**Comment by Dexterp37** [comment]
> 
> 
> > Ah, scrape that. This would work in mozilla/glean, but not in a-c. How would we fix it there?
> 
> Could we skip the assertion check in `Glean.initialize` if `Dispatchers.testingMode` is true?

Integration tests should not be in test mode, I think

**Comment by mdboom** [comment]
> Integration tests should not be in test mode, I think

Ah -- it's quite possible I just don't understand the moving parts.  I assumed since these tests use the `GleanTestRule` that `testingMode` would be set...

**Comment by Dexterp37** [comment]
> 
> 
> > Ah -- it's quite possible I just don't understand the moving parts. I assumed since these tests use the `GleanTestRule` that `testingMode` would be set...
> 
> I ... somehow didn't realize that.
> But I also think the application is launched once first before the test runner activates the rule and therefore that already fails?
> 
> I need to double check that again.

Garn, you're both right and I should have taken the full day off. We're in test mode. Sorry for the noise @mdboom and @badboy!

**Comment by badboy** [comment]
> Garn, you're both right and I should have taken the full day off. We're in test mode. 

No, absolutely helpful to raise this, because ... I wrote and merged #378 exactly because something was loaded before test mode.

**Comment by Dexterp37** [comment]
I've slightly worked around this in mozilla-mobile/android-components#4786 -  The solution there, if accepted, should be ported here as well (for the newly added rule).

**Comment by brizental** [comment]
> Is there a bug for running these automatically on CircleCI later?

I thought there was but I couldn't find it :/

**Comment by Dexterp37** [comment]
> 
> 
> This looks great! One thing that we may want to file a follow up bug for is we now have a lot of metrics that expire on `2100-01-01`, which may promote some bad habits. @Dexterp37 pointed this out to me last week on something I was working on so let's see what he says here.

Hey @travis79 that's true, good catch. However, I'm afraid in this specific case there isn't much we could do: this is an instrumented test that runs on real metrics (and potentially real devices). So we either set the date to a closer one and live with the fact that this might break soon-ish due to expiration, or just set it as a long distant future date and be done with it :)

I think I suggested to change that in your article, which serves a different purpose: that's a narrative for creating Glean SDK based stuff.

**Comment by travis79** [comment]
> > This looks great! One thing that we may want to file a follow up bug for is we now have a lot of metrics that expire on `2100-01-01`, which may promote some bad habits. @Dexterp37 pointed this out to me last week on something I was working on so let's see what he says here.
> 
> Hey @travis79 that's true, good catch. However, I'm afraid in this specific case there isn't much we could do: this is an instrumented test that runs on real metrics (and potentially real devices). So we either set the date to a closer one and live with the fact that this might break soon-ish due to expiration, or just set it as a long distant future date and be done with it :)
> 
> I think I suggested to change that in your article, which serves a different purpose: that's a narrative for creating Glean SDK based stuff.

No worries, 80 years just seemed like an optimistic lifespan of the Glean library.  

With this being an example that people may look at to figure out how to integrate Glean, I thought it might have the same visibility as my article, which is what led me to point it out.  

I definitely don't want to block on this, but if we added this to the probe-scraper dictionary we could get notifications when a more realistic date was about to expire, even if that was 5 years in the future, rather than 80.

**Comment by Dexterp37** [comment]
> With this being an example that people may look at to figure out how to integrate Glean, I thought it might have the same visibility as my article, which is what led me to point it out.

I think (and hope!) that your article will be viewed much more than these tests :)

> I definitely don't want to block on this, but if we added this to the probe-scraper dictionary we could get notifications when a more realistic date was about to expire, even if that was 5 years in the future, rather than 80.

I'd honestly be a bit hesitant to add this example to the probe-scraper (which gleans the data for the probe-dictionary). It's basically a test.

**Pull request merged**
