### PR TITLE
Try out new crates.io index protocol to speed up builds

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
Timing on current `main` ([this run](https://firefox-ci-tc.services.mozilla.com/tasks/SbHN9zTEToKt24QkQ2d3MA/runs/0/logs/live/public/logs/live.log)):

```
[task 2023-01-31T09:08:54.942Z] + cargo clippy --verbose --all --all-targets --all-features -- -D warnings
[task 2023-01-31T09:08:55.192Z]     Updating crates.io index
[task 2023-01-31T09:09:28.546Z]  Downloading crates ...
```

-> ~33seconds between updating and downloading.

**Comment by badboy** [comment]
New run:

```
[task 2023-02-01T09:40:52.708Z] + cargo clippy --verbose --all --all-targets --all-features -- -D warnings
[task 2023-02-01T09:40:52.905Z]     Updating crates.io index
[task 2023-02-01T09:40:54.491Z]  Downloading crates ...
```

-> less than 2 seconds.

**Comment by badboy** [comment]
overall runtime old: 268.013 seconds
overall runtime new: 190.52 seconds

don't know where, if and how it saved another 40 seconds, but I won't say no to that!

**Review by travis79 — APPROVED** [review]
-40s huh?  I'll take it!

**Pull request merged**
