### PR TITLE
Bug 1761485 - Add deprecated imports statements to ErrorType.

### PR DESCRIPTION
**Pull request by tawahpeggy**

### CODE REVIEW

**Review by Dexterp37 — CHANGES_REQUESTED** [review]
Hey @tawahpeggy ! Thank you for this PR! I think the only thing that was left to do in your bug was to update the docs. This PR only changes the changelog, which is not needed in this repo.

**Comment by tawahpeggy** [comment]
Hello, @Dexterp37 Thank you for your review. I haven't been able to see the document which tells me how to add the required deprecated imports. so please a little help will go a long way, thank you.

**Comment by Dexterp37** [comment]
> Hello, @Dexterp37 Thank you for your review. I haven't been able to see the document which tells me how to add the required deprecated imports. so please a little help will go a long way, thank you.

Hey @tawahpeggy ! At [this link](https://searchfox.org/glean/search?q=import+%7B+ErrorType+%7D+from+%22%40mozilla%2Fglean%2F&path=*.md&case=false&regexp=false) you can find the paths for all the occurrences that need to be changed within this repository. They need to be changed to `import { ErrorType } from "@mozilla/glean/error";` as per your last PR.

**Comment by tawahpeggy** [comment]
Hello @Dexterp37, Thank you very much for your help, ErrorType import has been replaced on all required files from platforms to error and I have also removed the update on CHANGELOG.md. The issue now is, some tests on CI/CD fail and i have been trying to resolve them, my rust, pip and python version is up to date so i do not know why the tests fail.

**Review by Dexterp37 — APPROVED** [review]
Thank you!

**Comment by tawahpeggy** [comment]
Great, thank you very much. Moving to the next issue now.

**Pull request merged**
