### PR TITLE
Upgrade to uniffi 0.19

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Review by chutten — APPROVED** [review]
I'd love if the commit message or PR explained why (even if it's just "because keeping up to date is good hygiene")

**Comment by badboy** [comment]
> I'd love if the commit message or PR explained why (even if it's just "because keeping up to date is good hygiene")

Will add it. Right now the 0.19.1 release is broken for us anyway and I need to wait for a new one,.

**Comment by travis79** [comment]
UniFFI version 19.2 seems to work according to my local build and CI. The rust-beta-tests are a [separate problem](https://github.com/mozilla/glean/pull/2107)

**Comment by badboy** [comment]
> UniFFI version 19.2 seems to work according to my local build and CI. The rust-beta-tests are a [separate problem](https://github.com/mozilla/glean/pull/2107). @badboy I can't flag you for review since this is your PR, but if you don't mind taking a look before this is landed (when you are back, of course)

yup, landing this, then we can pull in #2107 as well and get to a release soon.

**Pull request merged**
