### PR TITLE
Extend the sdk_generator.sh script to support more features

### PR DESCRIPTION
**Pull request by badboy**
https://bugzilla.mozilla.org/show_bug.cgi?id=1585298

### CODE REVIEW

**Comment by badboy** [comment]
I actually found out that we might be able to surface warnings from the linter, see e.g. https://medium.com/ios-os-x-development/highlight-warnings-in-xcode-521125121a75

**Comment by badboy** [comment]
(I'll file a follow up bug though)

**Comment by badboy** [comment]
-> https://bugzilla.mozilla.org/show_bug.cgi?id=1601974

**Comment by travis79** [comment]
> I actually found out that we might be able to surface warnings from the linter, see e.g. [medium.com/ios-os-x-development/highlight-warnings-in-xcode-521125121a75](https://medium.com/ios-os-x-development/highlight-warnings-in-xcode-521125121a75)

This is cool!

**Pull request merged**
