### PR TITLE
Bug 1838174 - Upgrade to Gradle 8.2.1 and Android Gradle Plugin 8.0.2 [ci full]

### PR DESCRIPTION
**Pull request by badboy**
Supersedes #2500

### CODE REVIEW

**Comment by badboy** [comment]
There's still some warnings during packaging:

<details>

```
[task 2023-06-27T08:56:38.600Z] > Task :glean:releaseSourcesJar
[task 2023-06-27T08:56:38.600Z] Encountered duplicate path "main/mozilla/telemetry/glean/Dispatchers.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.600Z] Encountered duplicate path "main/mozilla/telemetry/glean/Glean.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.601Z] Encountered duplicate path "main/mozilla/telemetry/glean/config/Configuration.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/debug/GleanDebugActivity.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/net/BaseUploader.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/net/HttpURLConnectionUploader.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/net/PingUploader.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/net/Upload.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/private/Aliases.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/private/BooleanMetricType.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/private/CounterMetricType.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/private/CustomDistributionMetricType.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/private/DatetimeMetricType.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/private/DenominatorMetricType.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/private/EventMetricType.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/private/HistogramBase.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/private/LabeledMetricType.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/private/MemoryDistributionMetricType.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/private/NumeratorMetricType.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/private/PingType.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/private/QuantityMetricType.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/private/RateMetricType.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/private/StringListMetricType.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/private/StringMetricType.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/private/TextMetricType.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/private/TimespanMetricType.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/private/TimingDistributionMetricType.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/private/UrlMetricType.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/private/UuidMetricType.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/scheduler/GleanLifecycleObserver.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/scheduler/MetricsPingScheduler.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/scheduler/PingUploadWorker.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/testing/ErrorType.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/testing/GleanTestLocalServer.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/testing/GleanTestRule.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/utils/DataPathUtils.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/utils/DateUtils.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/utils/GzipUtils.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/utils/JsonUtils.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/utils/LocaleUtils.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/utils/ThreadUtils.kt" during copy operation configured with DuplicatesStrategy.WARN
[task 2023-06-27T08:56:38.602Z] Encountered duplicate path "main/mozilla/telemetry/glean/utils/WorkManagerUtils.kt" during copy operation configured with DuplicatesStrategy.WARN
```

</details>

**Comment by badboy** [comment]
I still need to test that the `GleanMetricsYamlTransform` part works as expected in Fenix.

**Comment by badboy** [comment]
fwiw I looked at https://stackoverflow.com/questions/71365373/software-components-will-not-be-created-automatically-for-maven-publishing-from and https://developer.android.com/build/publish-library/configure-pub-variants to understand that `singleVariant` part

**Comment by badboy** [comment]
> I still need to test that the `GleanMetricsYamlTransform` part works as expected in Fenix.

Done.

**Review by travis79 — APPROVED** [review]

**Comment by mcarare** [comment]
The Gradle part LGTM!

**Review by travis79 — APPROVED** [review]

**Pull request merged**
